version: '3.8'
services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=600
      - GRID_TIMEOUT=600
      - GRID_SESSION_TIMEOUT=600
      - GRID_NEW_SESSION_WAIT_TIMEOUT=30

  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_SESSION_TIMEOUT=600
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1

  firefox:
    image: selenium/node-firefox:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_SESSION_TIMEOUT=600
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1